[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.sqls]
command = "sqls"

[[language]]
name = "sql"
language-servers = [ "sqls" ]

[language-sever.rust-analyzer]
# Enable all inlay hints
inlayHints.enable = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validate = true
schemaStore = { enable = true }
