[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]
